### ISSUE TITLE
Add Open Graph metadata to blog post to improve social share snippet

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/coopdevs-old-web#15]
https://developers.facebook.com/docs/sharing/webmasters

**Comment by sauloperez** [comment]
Can we explain a bit more what needs to be implemented here @sseerrggii ? It'd be great to have it done for the Hacktoberfest.

**Comment by sseerrggii** [comment]
In order to show correct snippet in social shares we want to use Open Graph metatags in Post show:

`<meta property="og:title" content="Post title" />`
`<meta property="og:description" content="Te first characters of Post" />`
`<meta property="og:image" content="URL of first image in Post" /> `

**Comment by enricostano** [comment]
Interesting

**Comment by lumie31** [comment]
Hello @sseerrggii If I'm clear about this issue, you want the above `meta` tags to be added to the `head.html` file in the `_includes` directory to improve social share snippet?

If that seems to be what you want, I'd want to jump on this issue. Although since I'm on windows, I have issues working with `ruby` projects except if a docker image exists which @sauloperez helped out with in another repository from this organization. 

Also, do you think it's a good idea to add the `meta` tags without building/running/testing out the project? If this seems okay by you, I could make the fix ASAP.

**Comment by sseerrggii** [comment]
Welcome @lumie31 thanks for your help :heart: 

Yes, it's like your explanation but we want to add de `og:` meta tags **only for blog posts** 

I will test it. So you can create the PR and I will give feedback ;)

**Comment by sauloperez** [comment]
I hear you @lumie31 and created https://github.com/coopdevs/coopdevs.github.io/issues/97. Feel free to pick it up. You might familiar with the topic now

**Comment by lumie31** [comment]
Way to go @sseerrggii Will make the fix right away and drop a comment here when I'm done. Also @sauloperez I checked out your reference above and I think I'm up for the challenge, will make any other comment as regards your comment above in the referenced issue #97

**Comment by sauloperez** [comment]
awesome @lumie31 ! keep it up! :muscle:

**Comment by sauloperez** [comment]
Too late @lumie31 https://github.com/coopdevs/coopdevs.github.io/pull/98 :sweat_smile:

**Comment by lumie31** [comment]
> Too late @lumie31 #98 😅

Sad 😢 Really wanted to jump on this

**Comment by lumie31** [comment]
@sseerrggii I raised a PR on #99. Kindly review

**Comment by sauloperez** [comment]
> > Too late @lumie31 #98 sweat_smile
> 
> Sad  Really wanted to jump on this

you can always find a side project as excuse to play with Docker until we create an issue about it in any other project of ours :joy:
